{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  -  {{ include "chart.fullname" . }}
  http:
  {{- range .Values.ingress.hosts }}
  - match:
    route:
    - destination:
        host: {{ .host | quote }}
        port:
          number: {{ $svcPort }}
  {{- end }}
